/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'deepakrohan' at '9/5/16 3:18 PM' with Gradle 2.14.1
 *
 * @author deepakrohan, @date 9/5/16 3:18 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
